backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

local_backend: true
media_folder: static/images
public_folder: /images

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/data/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "blog-page",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Image", name: "image", widget: "image"}
      - {
          label: "Publish Date",
          name: "date",
          widget: "datetime",
          default: "",
          date_format: "DD.MM.YYYY",
          time_format: "false",
        }
      - { label: "Tags",
          name: "tags", 
          widget: "list",
          fields:
            [
              { label: "Tag", name: "tag", widget: "string"}
            ]
        }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/data/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "index-page",
            }

          - {
              label: "Hero",
              name: "hero",
              widget: "object",
              fields:
                [
                  { label: TitleUp, name: titleUp, widget: string },
                  { label: TitleDown, name: titleDown, widget: string },
                  { label: Image, name: image, widget: image },
                  { label: Description, name: description, widget: text },
                  {
                    label: Button,
                    name: ctaButton,
                    widget: list,
                    fields:
                      [
                        { label: Text, name: text, widget: string },
                        { label: Link, name: link, widget: string },
                      ],
                  },
                ],
            }

          - {
              label: Services,
              name: services,
              widget: object,
              fields:
                [
                  { label: ServiceImage, name: serviceImage, widget: image },
                  { label: Tag, name: tag, widget: string },
                  { label: title, name: title, widget: string },
                  { label: Description, name: description, widget: string },
                  {
                    label: Service,
                    name: service,
                    widget: list,
                    min: 3,
                    max: 6,
                    fields:
                      [
                        { label: Title, name: title, widget: string },
                        {
                          label: Logo,
                          name: logo,
                          widget: object,
                          fields:
                            [
                              { label: Icon, name: icon, widget: icon },
                              { label: BgColor, name: bgColor, widget: color },
                            ],
                        },
                      ],
                  },
                ],
            }

          - {
              label: Testimonials,
              name: testimonials,
              widget: object,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: Description, name: description, widget: string },
                  {
                    label: Testimonial,
                    name: testimonial,
                    widget: list,
                    fields:
                      [
                        { label: Title, name: title, widget: string },
                        {
                          label: Description,
                          name: description,
                          widget: string,
                        },
                        { label: Profile, name: profile, widget: image },
                        { label: Name, name: name, widget: string },
                        { label: Bio, name: bio, widget: string },
                      ],
                  },
                ],
            }

          - {
              label: Contact,
              name: contact,
              widget: object,
              fields:
                [
                  { label: PhoneNumber, name: phoneNumber, widget: string },
                  { label: Email, name: email, widget: string },
                  { label: Address, name: address, widget: text },
                ],
            }

          - {
              label: "Blurbs",
              name: "blurbs",
              widget: object,
              fields:
                [
                  {
                    label: "BlogList",
                    name: "blogList",
                    widget: list,
                    fields:
                      [
                        {
                          label: "Blurb", 
                          name: "blurb", 
                          widget: "relation", 
                          collection: "blog", 
                          search_fields: ['title'], 
                          value_field: "title", 
                        }
                      ],
                  }
                ],
            }
